# GuildWars Configuration

# General settings
general:
  # The term used to refer to guilds (e.g., 'guild', 'faction', 'clan', 'club')
  # This affects display messages but not commands
  group-term: 'guild'
  
  # Whether the TreeFeller feature is enabled
  # When enabled, breaking the bottom log of a tree will fell the entire tree
  treefeller: true
  
  # Custom enchantments settings
  custom-enchantments:
    # Chance to get custom enchantments from enchantment tables (1 in X chance)
    enchantment-table-chance: 1000
    
    # Chance to get custom enchantments from loot chests (1 in X chance)
    loot-chest-chance: 200
    
    # Whether custom enchantments can be found in the following locations
    locations:
      overworld-structures: true   # Desert temples, jungle temples, etc.
      end-cities: true             # End city chests
      nether-fortresses: true      # Nether fortress chests
      
  # Visual effects settings
  visual-effects:
    # Health bar settings
    health-bars:
      # Whether to show health bars above mobs
      enabled: true
      
      # Maximum distance (in blocks) from which health bars are visible
      max-distance: 24
      
      # Whether health bars can be seen through walls
      visible-through-walls: false
      
      # Duration in seconds before removing a health bar if entity is not updated
      cleanup-time: 60
  
  # Custom mob settings
  custom-mobs:
    # Whether natural spawning of custom mobs is enabled
    natural-spawning: true
    
    # Corrupted Warden settings
    corrupted-warden:
      # Chance to replace natural mob spawns in plains biomes (0.0-1.0)
      spawn-rate: 0.15
      
      # Maximum number of Corrupted Wardens allowed in the world at once
      max-spawned: 5
      
      # Whether Corrupted Wardens should target players
      target-players: true
    
    # Frost Giant settings
    frost-giant:
      # Chance to replace natural mob spawns in cold biomes (0.0-1.0)
      spawn-rate: 0.10
      
      # Maximum number of Frost Giants allowed in the world at once
      max-spawned: 3
      
      # Whether Frost Giants should target players
      target-players: true
      
  # Performance optimization settings
  performance:
    # Mob merging (stacking) settings
    mob-merging:
      # Whether to enable mob merging in chunks to reduce lag
      enabled: true
      
      # Maximum number of similar mobs that can be merged into one stack
      max-stack-size: 10
      
      # Types of mobs to exclude from merging (e.g., VILLAGER, IRON_GOLEM)
      excluded-types:
        - VILLAGER
        - WANDERING_TRADER
        - IRON_GOLEM
        - ENDER_DRAGON
        - WITHER
    
    # Clear lag settings
    clear-lag:
      # Whether to enable periodic clearing of ground items
      enabled: true
      
      # Time in minutes between clearing ground items
      interval: 5
      
      # Warning time in seconds before items are cleared
      warning-time: 60
      
      # Types of entities to exclude from clearing
      excluded-types:
        - ARMOR_STAND
        - ITEM_FRAME
        - GLOW_ITEM_FRAME
        - PAINTING

# Command aliases
commands:
  # Custom command alias for the main guild command
  # This will allow players to use the specified alias instead of /guild
  # Example: Setting this to 'clan' will allow players to use /clan instead of /guild
  main-command-alias: 'guild'

# Placeholders
placeholders:
  # Chat tags for different guild roles
  tags:
    guild: '[G]'
    leader: '[Leader]'
    officer: '[Officer]'
    member: '[Member]'
  # Chat colors for different guild roles (using Minecraft color codes)
  colors:
    guild: '&7'
    leader: '&c'
    officer: '&9'
    member: '&a'
  # Chat format
  chat-format: '&8[&r%guild_name%&8] %role_color%%guild_role% &r%player_name%&8: &r%message%'

# Guild settings
guilds:
  # Minimum number of players required to create a guild
  min-players-to-create: 1
  
  # Maximum number of players allowed in a guild
  max-players: 30
  
  # Cost to create a guild (if economy plugin is installed)
  creation-cost: 1000.0
  
  # Cooldown between creating guilds (in hours)
  creation-cooldown: 24
  
  # Maximum length of guild name
  max-name-length: 16
  
  # Minimum length of guild name
  min-name-length: 3
  
  # Whether to allow color codes in guild names
  allow-color-codes: false
  
  # Guild home settings
  home:
    # Whether guilds can set homes
    enabled: true
    
    # Cooldown between teleports (in seconds)
    teleport-cooldown: 60
    
    # Delay before teleporting (in seconds)
    teleport-delay: 3

# Territory settings
territory:
  # Whether territory claiming is enabled
  enabled: true
  
  # Maximum number of chunks a guild can claim
  max-claims: 50
  
  # Cost per claim (if economy plugin is installed)
  claim-cost: 100.0
  
  # Whether to allow claiming in specific worlds
  worlds:
    - 'world'
    - 'world_nether'
    - 'world_the_end'
  
  # Protection settings
  protection:
    # Whether to prevent non-members from breaking blocks
    prevent-block-break: true
    
    # Whether to prevent non-members from placing blocks
    prevent-block-place: true
    
    # Whether to prevent non-members from interacting with blocks
    prevent-block-interact: true
    
    # Whether to prevent non-members from attacking members
    prevent-pvp: true
    
    # Whether to prevent non-members from using items
    prevent-item-use: true

# War settings
war:
  # Whether war system is enabled
  enabled: true
  
  # Minimum duration of war (in minutes)
  min-duration: 30
  
  # Maximum duration of war (in minutes)
  max-duration: 120
  
  # Cooldown between wars (in hours)
  cooldown: 24
  
  # Whether to disable protection during wars
  disable-protection: true
  
  # Whether to enable friendly fire during wars
  friendly-fire: false

# Relations settings
relations:
  # Whether alliance system is enabled
  alliances-enabled: true
  
  # Maximum number of alliances a guild can have
  max-alliances: 3
  
  # Whether enemy system is enabled
  enemies-enabled: true
  
  # Maximum number of enemies a guild can have
  max-enemies: 10

# Permissions
# These are the permissions used by the plugin
# You can assign these to groups in your permissions plugin
permissions:
  # Basic permissions
  guildwars.create: true      # Allows creating guilds
  guildwars.join: true        # Allows joining guilds
  
  # Admin permissions
  guildwars.admin: false      # Gives access to all GuildWars commands
  guildwars.admin.delete: false # Allows deleting guilds as an administrator
  guildwars.admin.reload: false # Allows reloading the plugin configuration
  guildwars.admin.enchant: false # Allows applying custom enchantments
  guildwars.admin.give: false   # Allows giving special items
  guildwars.admin.summon: false # Allows summoning custom mobs
  guildwars.admin.godmode: false # Allows toggling godmode
  guildwars.admin.healthbar: false # Allows toggling health bars
  guildwars.admin.mobmerge: false # Allows controlling mob merging
  guildwars.admin.clearlag: false # Allows controlling clear lag
  guildwars.admin.mobspawn: false # Allows controlling custom mob spawning

# Messages
messages:
  prefix: '&8[&6GuildWars&8] &r'
  guild-created: '&aGuild %guild% has been created!'
  guild-disbanded: '&cGuild %guild% has been disbanded!'
  guild-joined: '&aYou have joined %guild%!'
  guild-left: '&cYou have left %guild%!'
  player-invited: '&aYou have invited %player% to join %guild%!'
  player-kicked: '&c%player% has been kicked from %guild%!'
  player-promoted: '&a%player% has been promoted in %guild%!'
  player-demoted: '&c%player% has been demoted in %guild%!'
  territory-claimed: '&aTerritory claimed for %guild%!'
  territory-unclaimed: '&cTerritory unclaimed from %guild%!'
  war-declared: '&c%guild1% has declared war on %guild2%!'
  war-ended: '&aThe war between %guild1% and %guild2% has ended!'
  alliance-formed: '&a%guild1% has formed an alliance with %guild2%!'
  alliance-broken: '&c%guild1% has broken their alliance with %guild2%!'
  enemy-declared: '&c%guild1% has declared %guild2% as an enemy!'
  enemy-removed: '&a%guild1% no longer considers %guild2% an enemy!'
